#!/usr/bin/env node
/*
  Builds the Tour Companion's data files from a PRIVATE input file that never
  goes in this repo:

    node events/2026/afp/companion/build-lineups.mjs ~/afp-2026-companion/lineups.private.json

  Writes, next to this script:
    lineups.js    each tour's three stops, AES-GCM encrypted with a key derived
                  (PBKDF2-SHA256) from that tour's QR code. Safe to publish.
    directory.js  the open hall directory (vendor, booth, optional text).
                  Public by design.

  And prints the four QR URLs. A tour without a code gets one generated and
  written back to the input file, so codes stay stable across rebuilds — a
  printed QR code keeps working after the lineup is edited.

  Input shape:
  {
    "sessions": {
      "s1": { "code": "",
              "stops": [ { "vendor": "", "booth": "", "time": "", "text": "" }, x3 ],
              "show":  [ ["10:15 - 10:22", "Opening and intro at the meetup"], ... ] },
      "s2": ..., "s3": ..., "s4": ...
    },
    "directoryText": true,
    "directory": [ { "vendor": "", "booth": "", "text": "" } ]
  }
  "show" is the tour's run of show, copied from the Vendor Tracker and Matrix
  workbook (AFP Tours sheet). "directoryText": false publishes the hall
  directory as names and booths only.
*/
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { webcrypto as crypto } from 'node:crypto';

const PAGE_URL = 'https://realtreasury.github.io/rt-wordpress-content/events/2026/afp/companion/';
const ITER = 150000;
const ALPHABET = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'; /* no 0/O, 1/I/L */

const input = process.argv[2];
if (!input) {
  console.error('usage: node build-lineups.mjs <path to lineups.private.json>');
  process.exit(2);
}
const here = dirname(fileURLToPath(import.meta.url));
const data = JSON.parse(readFileSync(input, 'utf8'));

function newCode() {
  const bytes = crypto.getRandomValues(new Uint8Array(10));
  return Array.from(bytes, (b) => ALPHABET[b % ALPHABET.length]).join('');
}
const b64 = (u8) => Buffer.from(u8).toString('base64');

async function encrypt(code, payload) {
  const enc = new TextEncoder();
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const base = await crypto.subtle.importKey('raw', enc.encode(code.trim().toUpperCase()), 'PBKDF2', false, ['deriveKey']);
  const key = await crypto.subtle.deriveKey({ name: 'PBKDF2', salt, iterations: ITER, hash: 'SHA-256' },
    base, { name: 'AES-GCM', length: 256 }, false, ['encrypt']);
  const ct = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, enc.encode(JSON.stringify(payload))));
  return { salt: b64(salt), iv: b64(iv), iter: ITER, ct: b64(ct) };
}

const str = (v) => String(v ?? '').trim();
const clean = (s) => ({ vendor: str(s.vendor), booth: str(s.booth), time: str(s.time), text: str(s.text) });

const lineups = {};
const urls = [];
let wroteCodes = false;
for (const id of ['s1', 's2', 's3', 's4']) {
  const s = (data.sessions || {})[id];
  if (!s) continue;
  if (!s.code) { s.code = newCode(); wroteCodes = true; }
  const stops = (s.stops || []).slice(0, 3).map(clean);
  const show = (s.show || []).map((r) => [str(r[0]), str(r[1])]);
  if (stops.some((x) => x.vendor)) lineups[id] = await encrypt(s.code, { stops, show });
  urls.push(`${id}  ${PAGE_URL}?tour=${id}&k=${s.code}${lineups[id] ? '' : '   (no vendors yet)'}`);
}

const banner = '/* Generated by build-lineups.mjs. Do not edit by hand. */\n';
writeFileSync(join(here, 'lineups.js'), banner + 'window.RT_LINEUPS = ' + JSON.stringify(lineups, null, 2) + ';\n');
const withText = data.directoryText !== false;
const directory = (data.directory || []).map(clean).filter((d) => d.vendor)
  .map((d) => ({ vendor: d.vendor, booth: d.booth, text: withText ? d.text : '' }));
writeFileSync(join(here, 'directory.js'), banner + 'window.RT_DIRECTORY = ' + JSON.stringify(directory, null, 2) + ';\n');
if (wroteCodes) writeFileSync(input, JSON.stringify(data, null, 2) + '\n');

console.log(`lineups.js: ${Object.keys(lineups).length} tour(s) encrypted; directory.js: ${directory.length} vendor(s)`);
console.log('QR URLs (one per tour):');
for (const u of urls) console.log('  ' + u);
