/* Generated by build-lineups.mjs. Do not edit by hand. */
window.RT_DIRECTORY = [
  {
    "vendor": "Agicap",
    "booth": "159",
    "text": "Agicap is the leading cash flow management platform for mid-market organizations according to G2. It is AI-powered, connecting your banking and accounting flows to unlock trapped liquidity. It includes cash management, cash forecasting, payments and transfers, collections, and bank reconciliation, all on one easy to use and easy to implement platform."
  },
  {
    "vendor": "Atlar",
    "booth": "2040",
    "text": "Atlar is the AI-native treasury platform for growth companies to manage cash, payments, forecasting, and liquidity. Teams at Bandwidth, Lovable, Flex, Oyster, and Tide connect every bank and ERP through connectivity that Atlar owns end to end — over €500B annualized across 100+ countries"
  },
  {
    "vendor": "Bottomline",
    "booth": "1731",
    "text": "Bottomline helps businesses transform the way they pay and get paid. A global leader in business payments and cash management, Bottomline’s secure, comprehensive solutions modernize payments for businesses and financial institutions globally. With over 35 years of experience, moving more than $16 trillion in payments annually, Bottomline is committed to driving impactful results for customers."
  },
  {
    "vendor": "FIS Integrity",
    "booth": "1353",
    "text": "Integrity is a cloud treasury platform that unifies cash visibility, forecasting, payments, foreign exchange, debt, accounting, compliance, reporting, and analytics. Its secure multitenant architecture enables seamless upgrades, connectivity, lower ownership costs, and Treasury GPT guidance, helping teams automate controls and manage treasury needs of any complexity confidently and efficiently."
  },
  {
    "vendor": "FIS Quantum",
    "booth": "1353",
    "text": "Quantum combines treasury, cash, risk, and accounting functionality with modern cloud agility. Built for enterprise scale, it supports complex asset classes, large data volumes, automation, API connectivity, and resilient microservices. A Treasury Data Hub, an AI-ready semantic model, and strong governance enable secure, scalable innovation across treasury environments."
  },
  {
    "vendor": "IT2 (ION)",
    "booth": "724",
    "text": "IT2 is a flexible treasury management solution that automates cash, payments, liquidity, debt, investments, FX, risk management, accounting, and reporting workflows. Available in the cloud or self-hosted, it offers extensive API capabilities and integration flexibility. Ideal for mid-to-large organisations seeking scalable treasury automation, connectivity, and operational efficiency."
  },
  {
    "vendor": "Reval (ION)",
    "booth": "724",
    "text": "Reval is a multi-tenant SaaS treasury and risk management solution with web-based access and integrated market data. It supports cash, liquidity, debt, investments, FX, interest rate and commodity risk, derivatives, hedge accounting, reporting, and compliance. Ideal for mid-to-large corporates seeking scalable cash and risk management capabilities."
  },
  {
    "vendor": "Wallstreet Suite (ION)",
    "booth": "724",
    "text": "Wallstreet Suite is a cloud and on-premises treasury and risk management platform that automates cash, payments, liquidity, investments, FX, commodities, derivatives, custody, and collateral workflows across a wide range of asset classes. Ideal for large global corporations, financial institutions, debt management offices and central banks requiring scalable operations, advanced risk management, and integration flexibility."
  },
  {
    "vendor": "Kyriba",
    "booth": "543",
    "text": "Kyriba’s comprehensive platform provides treasury & risk management, working capital optimization, payments automation, and bank connectivity. Powered by Trusted Agentic AI (TAI), advanced APIs, and real-time analytics, Kyriba delivers complete liquidity performance management with governed intelligence, enabling CFOs and treasurers to connect, protect, forecast, and optimize liquidity with confidence."
  },
  {
    "vendor": "Nilus",
    "booth": "361",
    "text": "Nilus is an agentic workforce for treasury. AI agents reconcile cash, forecast liquidity, hedge exposure, and put idle cash to work — all inside your controls. Your team sets the policy and the guardrails; the agents run the workflows underneath them, every day, whether you’re at your desk or away."
  },
  {
    "vendor": "Palm",
    "booth": "239",
    "text": "Palm is the AI intelligence layer that sits on top of your existing treasury systems and goes live in weeks with AI-cash forecasting, variance analysis, scenario modelling and AI agents to replace routine treasury tasks. No rip-and-replace. With Palm, ON Running unlocked $350M in additional cash investments with better visibility and higher confidence in forecasts."
  },
  {
    "vendor": "Panax",
    "booth": "1270",
    "text": "Panax is an AI-native treasury and cash operations platform that connects banks, ERPs, and financial systems into a unified data layer. It gives finance teams real-time visibility, automated reporting and reconciliation, intelligent forecasting and insights, and robust payment workflows - turning fragmented financial data into better decisions and controlled execution."
  },
  {
    "vendor": "Ripple Treasury",
    "booth": "835",
    "text": "Ripple Treasury, powered by GTreasury, gives CFOs and treasurers the tools to move beyond spreadsheets and fragmented systems. By centralizing financial data across banks, ERPs, and third-party platforms, it delivers real-time visibility into cash, liquidity, and risk — so treasury teams can act with confidence, not guesswork."
  },
  {
    "vendor": "Treasury Cube",
    "booth": "663",
    "text": "TreasuryCube is a Treasury Management System (TMS) purpose-built for mid-to-large corporates with complex treasury operations. We give treasury teams the infrastructure to see, control, and optimize cash and risk across the entire group, without the manual reconciliation and fragmented reporting that complexity usually forces on them."
  },
  {
    "vendor": "Treasury Curve",
    "booth": "972",
    "text": "Treasury Curve is the only platform that unifies cash management and investments in a single solution. Organizations gain real-time visibility, automated workflows, and access to thousands of banks and investment options through a flexible platform that can often be provided at no cost based on investment balances."
  },
  {
    "vendor": "Treasury Suite",
    "booth": "935",
    "text": "Treasury Suite is a simple, powerful TMS delivering rapid connectivity, historical analytics, categorization, GL reconciliation, intraday positioning, forecasting, bank account management, and bank fee benchmarking. Combined with Hamilton, our treasury-specific AI, it provides unmatched functionality, flexibility, and affordability for organizations across all industries, typically serving clients with $250M+ in revenue."
  },
  {
    "vendor": "Treasury4",
    "booth": "1863",
    "text": "Treasury4 is a treasury management platform built by former corporate treasurers. It gives finance teams clean, connected data across entities, cash, payments, debt, and FX, so they stop fixing spreadsheets and start making faster, more confident decisions. Built for treasury. Engineered for AI."
  },
  {
    "vendor": "Trovata TMS",
    "booth": "561",
    "text": "Trovata is a complete, AI-first TMS with conversational and agentic AI embedded across every module from cash and payments to sophisticated capital markets workflows. Its enterprise-grade, cloud-native platform unifies cash, liquidity, payments, risk, debt, investments, banking, and accounting. Trovata’s AI accelerates onboarding, automates work, and makes adding banks, entities, and new activities faster. An extensive bank API library and embedded stablecoin capabilities bridge traditional banking and programmable, real-time liquidity. Leading financial institutions including JPMorgan, Wells Fargo, Capital One, PNC, Mastercard, and State Street invest in Trovata and bring Trovata technology to their corporate clients."
  }
];
